name = "remix-cloudflare-workers"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[vars]
GRAPHQL_ENDPOINT="https://blue-surf-560029.us-east-1.aws.cloud.dgraph.io/graphql"